name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: cwill747-swamp
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check formatting
        run: nix develop --command cargo fmt --all --check

      - name: Clippy
        run: nix develop --command cargo clippy --all-targets --all-features -- -D warnings
